spring.application.name=alibabaai
server.port=8080

#??
#spring.ai.dashscope.api-key=sk-5f462474768a41f58f02ce4b1910f34c
#????
spring.ai.dashscope.api-key=sk-aa1b4f4f0e4d42fbbabc3ef980539bd1
spring.ai.dashscope.chat.options.model=qwen-max

#spring.ai.chat.client.enabled=false

spring.ai.alibaba.toolcalling.baidu.translate.enabled=true
spring.ai.alibaba.toolcalling.baidu.translate.app-id=20250902002444886
spring.ai.alibaba.toolcalling.baidu.translate.secret-key=M4hAnEmQOFJYlmcnVs22

spring.ai.alibaba.toolcalling.baidu.map.enabled=true
spring.ai.alibaba.toolcalling.baidu.map.apiKey=${BAIDU_MAP_API_KEY}
spring.ai.alibaba.toolcalling.time.enabled=true
spring.ai.alibaba.toolcalling.weather.enabled=true
spring.ai.alibaba.toolcalling.weather.api-key=${WEATHER_API_KEY}
spring.ai.alibaba.toolcalling.dashscope.api-key=sk-5f462474768a41f58f02ce4b1910f34c

spring.ai.mcp.client.toolcallback.enabled: true
spring.ai.mcp.client.streamable.connections.server1.url: http://127.0.0.1:12306/mcp/

# MCP Node.js path configuration (optional)
# mcp.node-path=C:\Program Files\nodejs\node.exe
# mcp.node-path=/usr/local/bin/node

