spring.application.name=alibabaai
server.port=8080

#??
#spring.ai.dashscope.api-key=sk-5f462474768a41f58f02ce4b1910f34c
#????
spring.ai.dashscope.api-key=sk-aa1b4f4f0e4d42fbbabc3ef980539bd1
spring.ai.dashscope.chat.options.model=qwen-max

#spring.ai.chat.client.enabled=false